### ISSUE TITLE
Some DDS files cannot be converted

### ISSUE THREAD

**Issue by lazydevyo** [scorpdx/ddstronk#1]
This is what I get when I drop a single dds file that is not supported apparently.
```

Unhandled exception. System.AggregateException: One or more errors occurred. (Errors during bulk conversion (The method or operation is not implemented.))
 ---> System.AggregateException: Errors during bulk conversion (The method or operation is not implemented.)
 ---> System.NotImplementedException: The method or operation is not implemented.
   at DDStronk.BulkConverter.Convert(String path)
   at DDStronk.BulkConverter.ProcessLoop()
   --- End of inner exception stack trace ---
   at DDStronk.BulkConverter.ProcessLoop()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at DDStronk.BulkConverter.Dispose(Boolean disposing)
   at DDStronk.Program.Main(String[] args)

```

**Comment by F1mmel** [comment]
Same here, any fixes?
